# Copyright (c) 2024 Fabian Pflug
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    path: ble_door_sensor

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.4.1
      import:
        name-allowlist:
          - cmsis_6
          - hal_nordic
          - zcbor
          - mcuboot
